# Generated by Django 6.0 on 2026-01-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.PositiveBigIntegerField(max_length=15),
        ),
    ]
