# Generated by Django 6.0 on 2026-01-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.PositiveBigIntegerField(max_length=15),
        ),
    ]
