# Generated by Django 6.0 on 2026-02-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_awb_code_order_shipment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipment_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
